# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bb1d408f6395bc5d5b1f4f52055bcd31ff2ed149ca7a5873f9d127ec396466d206b1c447cafa9008bddfb353c8af14736e65a14dc966441c4fc1fd191050bb7

test:
  secret_key_base: 9d277ffa45af43dc49d66e958a4e8c9fcbcef05b3759bf7f430009bdcaefccda67ef82b795e87f52b89fad9339d2f04f1b4fe04295431a64762990a3a3e73d23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
